[workspace]
members = [
    "common",
    "common-test",
    "pubsub",
    "floodsub",
]

[workspace.dependencies]
assert_matches = "1.5.0"
bytes = "1.4"
futures = "0.3"
libp2p = "0.52"
prost = "0.12"
thiserror = "1.0"
tokio = "1.32"
tracing = "0.1"
