[workspace]
members = [
    "common",
    "common-test",
    "floodsub",
]

[workspace.dependencies]
anyhow = "1.0"
assert_matches = "1.5.0"
bytes = "1.4"
futures = "0.3"
libp2p = "0.52"
thiserror = "1.0"
tokio = "1.32"
