name: ci
on:
  pull_request:
  push:
    branches:
    - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: "build and test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v1

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Protoc's Prost plugin
        uses: baptiste0928/cargo-install@v2
        with:
          crate: protoc-gen-prost

      - name: Install Protoc's Prost crate plugin
        uses: baptiste0928/cargo-install@v2
        with:
          crate: protoc-gen-prost-crate

      - name: Install Cargo LLVM cov
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-llvm-cov

      - name: Install Cargo nextest
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-nextest

      - name: Build
        run: cargo build

      - name: Run unit tests
        run: cargo llvm-cov nextest r --lib --lcov --output-path ut-lcov.info

      - name: Run integration tests
        run: cargo llvm-cov nextest r --test '*' --lcov --output-path it-lcov.info

      - name: Upload unit tests coverage report to codecov
        uses: codecov/codecov-action@v3
        with:
          files: ut-lcov.info
          flags: unit

      - name: Upload integration tests coverage report to codecov
        uses: codecov/codecov-action@v3
        with:
          files: it-lcov.info
          flags: integration
